export enum ServiceRuntimeState {
  INITIALIZING = 'INITIALIZING',
  NOT_RUNNING = 'NOT_RUNNING',
  PARTLY_RUNNING = 'PARTLY_RUNNING',
  RUNNING = 'RUNNING',
  STARTING = 'STARTING',
  STOPPING = 'STOPPING',
  UNKNOWN  = 'UNKNOWN'
}
