export enum TransportOrderType {
  NO,
  UNSPECIFIED,
  MANUAL,
  STORAGE,
  RETRIEVAL,
  INTERNAL_RELOCATION_OF_HIDING,
  INTERNAL_RELOCATION_FOR_CENTERING,
  INTERNAL_RELOCATION_FOR_DEFRAGMENTATION,
  INTERNAL_STOREBACK,
  INTERNAL_EVACUATION
}
